UPDATE creature_template SET ScriptName = 'npc_daphne_stilwell' WHERE entry = 6182;
UPDATE creature_template SET ScriptName = 'npc_horatio_lane_42308' WHERE entry = 42308;
UPDATE creature_template SET ScriptName = 'npc_west_plains_drifters' WHERE entry = 42391;
UPDATE creature_template SET ScriptName = 'npc_transient' WHERE entry = 42383;
UPDATE creature_template SET ScriptName = 'npc_homeless_stormwind_citizen_42384' WHERE entry = 42384;
UPDATE creature_template SET ScriptName = 'npc_homeless_stormwind_citizen_42386' WHERE entry = 42386;
UPDATE creature_template SET ScriptName = 'npc_ragamuffin_42413' WHERE entry = 42413;
UPDATE creature_template SET ScriptName = 'npc_lues_old_house' WHERE entry = 42500;
UPDATE creature_template SET ScriptName = 'npc_shadowy_figure' WHERE entry = 42515;
UPDATE creature_template SET ScriptName = 'npc_thug' WHERE entry = 42387;
UPDATE creature_template SET ScriptName = 'npc_horatio_lane_42558' WHERE entry = 42558;
UPDATE creature_template SET ScriptName = 'npc_overloaded_harvest_golem_42381' WHERE entry = 42381;
UPDATE creature_template SET ScriptName = 'npc_salma_saldean' WHERE entry = 235;
UPDATE creature_template SET ScriptName = 'npc_sentinel_hill_guard' WHERE (entry = 42407) OR (entry = 51915);
UPDATE creature_template SET ScriptName = 'npc_riverpaw_sentinel_hill' WHERE (entry = 54371) OR (entry = 54372) OR (entry = 54373);
UPDATE creature_template SET ScriptName = 'npc_defias_sentinel_hill' WHERE (entry = 449) OR (entry = 589) OR (entry = 594);
UPDATE creature_template SET ScriptName = 'npc_riverpaw_westfall' WHERE (entry = 124) OR (entry = 452) OR (entry = 501);
UPDATE creature_template SET ScriptName = 'npc_ripsnarl_sentinel_hill' WHERE entry = 42635;
UPDATE creature_template SET ScriptName = 'npc_agent_kearnen' WHERE entry = 7024;
UPDATE item_script_names_template SET ScriptName = 'item_potion_of_shrouding' WHERE id = 58112;
UPDATE creature_template SET ScriptName = 'npc_helix_gearbreaker' WHERE entry = 42655;
UPDATE creature_template SET ScriptName = 'npc_van_cleef_dummy' WHERE entry = 42679;
UPDATE creature_template SET ScriptName = 'npc_moonbrook_player_trigger_43515' WHERE entry = 43515;
UPDATE creature_template SET ScriptName = 'npc_vision_of_the_past' WHERE entry = 42693;
UPDATE creature_template SET ScriptName = 'npc_marshal_gryan_stoutmantle_234' WHERE entry = 234;
UPDATE creature_template SET ScriptName = 'npc_lieutenant_horatio_laine_42744' WHERE entry = 42744;
UPDATE creature_template SET ScriptName = 'npc_stormwind_investigator_42745' WHERE entry = 42745;
UPDATE creature_template SET ScriptName = 'npc_Ripsnarl_42748' WHERE entry = 42748;
UPDATE creature_template SET ScriptName = 'npc_hope_saldean_42749' WHERE entry = 42749;
UPDATE creature_template SET ScriptName = 'npc_marshal_gryan_stoutmantle_42750' WHERE entry = 42750;
UPDATE creature_template SET ScriptName = 'npc_captain_danuvin_42751' WHERE entry = 42751;
UPDATE creature_template SET ScriptName = 'npc_scout_galiaan_42752' WHERE entry = 42752;
UPDATE creature_template SET ScriptName = 'npc_helix_gearbreaker_42753' WHERE entry = 42753;
UPDATE creature_template SET ScriptName = 'npc_glubtok_42755' WHERE entry = 42755;
UPDATE creature_template SET ScriptName = 'npc_defias_blackguard_42769' WHERE entry = 42769;
UPDATE creature_template SET ScriptName = 'npc_thor_523' WHERE entry = 523;
