UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_gorgal_angerscar_34634' WHERE  entry = 34634;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_shoe_34638' WHERE  entry = 34638;
UPDATE `gameobject_template` SET `AIName`='', `ScriptName`='go_red_raptor_nest_6906' WHERE  entry = 6906;
UPDATE `gameobject_template` SET `AIName`='', `ScriptName`='go_blue_raptor_nest_6907' WHERE  entry = 6907;
UPDATE `gameobject_template` SET `AIName`='', `ScriptName`='go_yellow_raptor_nest_6908' WHERE  entry = 6908;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_wyneth_34846' WHERE  entry = 34846;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_verog_the_dervish_3395' WHERE  entry = 3395;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_trapped_wolf_34285' WHERE  entry = 34285;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_chain_origin_34287' WHERE  entry = 34287;
UPDATE `gameobject_template` SET `AIName`='', `ScriptName`='go_wolf_chains' WHERE  entry IN (195001, 195003, 195004);
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_halga_bloodeye_34258' WHERE  entry = 34258;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_lead_caravan_kodo_34430' WHERE  entry = 34430;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_balgor_whipshank_34431' WHERE  entry = 34431;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='vehicle_riding_shotgun_34438' WHERE  entry = 34438;
DELETE FROM `spell_script_names` WHERE spell_id = 65485;
INSERT INTO `spell_script_names` VALUES (65485, 'spell_mount_caravan_kodo_cue_65485');
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_razormane_raider_34487' WHERE  entry = 34487;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_razormane_pillager_34503' WHERE  entry = 34503;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_hogtied_razormane_34514' WHERE  entry = 34514;
INSERT INTO `areatrigger_scripts` VALUES (5465, 'at_groldoms_farm_5465');
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_togrik_34513' WHERE  entry = 34513;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_captured_razormane_34523' WHERE  entry = 34523;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_groldom_kodo_34547' WHERE  entry = 34547;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_fez_34543' WHERE  entry = 34543;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_rocco_whipshank_34578' WHERE  entry = 34578;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_head_caravan_kodo_34577' WHERE  entry = 34577;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='vehicle_hotseat_34582' WHERE  entry = 34582;
DELETE FROM `spell_script_names` WHERE spell_id = 65669;
INSERT INTO `spell_script_names` VALUES (65669, 'spell_mount_caravan_kodo_cue_part2_65669');
UPDATE `creature_template` SET `AIName`='', `ScriptName`='vehicle_burning_blade_mount_34593' WHERE  entry = 34593;
UPDATE `creature_template` SET `AIName`='', `ScriptName`='npc_burning_blade_raider_34594' WHERE  entry = 34594;
INSERT INTO `areatrigger_scripts` VALUES (5482, 'at_caravan_scene_5482');
INSERT INTO `areatrigger_scripts` VALUES (5483, 'at_follow_the_tracks_5483');
